import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Laughing Coyote | Development & Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Header />
        <main className="bg-munsell h-[750px] flex justify-center items-center">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
